export const textCardsEng = [
    // Primeiro Bloco
    { eng: "Ok, i'm listening. Spill", por: "Ok, estou ouvindo. Desembucha", id: 1 },
    { eng: "You know what?", por: "Quer saber?", id: 2 },
    { eng: "Of course!", por: "Claro", id: 3 },
    { eng: "Never mind", por: "Deixa pra lá", id: 4 },
    { eng: "Do you remember?", por: "Você se lembra?", id: 5 },
    { eng: "That’s nice!", por: "Que legal!", id: 6 },
    { eng: "Oh, you bet!", por: "Ah, pode apostar!", id: 7 },
    { eng: "What happened?", por: "O que aconteceu?", id: 8 },
    { eng: "You are my hero!", por: "Você é meu herói!", id: 9 },
    { eng: "How are you doing?", por: "Como você está?", id: 10 },
    { eng: "Oh yeah, that’s right.", por: "Ah sim, é isso mesmo", id: 11 },
    { eng: "Great choice!", por: "Ótima escolha!", id: 12 },
    { eng: "What are you in the mood for?", por: "O que você está com vontade de beber?", id: 13 },
    { eng: "Who’s that in that picture?", por: "Quem é aquela naquela foto?", id: 14 },
    { eng: "I’m gonna be a dad!", por: "Eu vou ser pai!", id: 15 },
    { eng: "I’m so happy for you!", por: "Eu estou muito feliz por vocês!", id: 16 },
    { eng: "Are you busy this afternoon?", por: "Você está ocupado hoje à tarde?", id: 17 },
    { eng: "Sounds exciting", por: "Parece empolgante", id: 18 },
    { eng: "What are we doing?", por: "O que vamos fazer?", id: 19 },
    { eng: "How’s the week looking?", por: "Como está a semana?", id: 20 },
    // Segundo Bloco
    { eng: "", por: "", id: 21 },
    { eng: "", por: "", id: 22 },
    { eng: "", por: "", id: 23 },
    { eng: "", por: "", id: 24 },
    { eng: "", por: "", id: 25 },
    { eng: "", por: "", id: 26 },
    { eng: "", por: "", id: 27 },
    { eng: "", por: "", id: 28 },
    { eng: "", por: "", id: 29 },
    { eng: "", por: "", id: 30 },
    { eng: "", por: "", id: 31 },
    { eng: "", por: "", id: 32 },
    { eng: "", por: "", id: 33 },
    { eng: "", por: "", id: 34 },
    { eng: "", por: "", id: 35 },
    { eng: "", por: "", id: 36 },
    { eng: "", por: "", id: 37 },
    { eng: "", por: "", id: 38 },
    { eng: "", por: "", id: 39 },
    { eng: "", por: "", id: 40 },
];
